#!/bin/bash

DIR="."
OUT=$DIR/ipop-tincan.out
ERR=$DIR/ipop-tincan.err
LOG=$DIR/ipop-gvpn.log

CONF=config-stun.json

# start tincan daemon
startTincan () {
    echo "Starting ipop-tincan ..."
    /opt/ipop/ipop-tincan > $OUT 2> $ERR &
}

# start controller
startController () {
    echo "Starting gvpn_controller ..."
    /opt/ipop/gvpn_controller.py -c $CONF &> $LOG &
}

