#!/bin/bash

# Shut down ipop  processes

kill_ipop_tincan () {
daemon="ipop-tincan"
PID=`ps -ef | grep $daemon | grep -v grep | awk '{print $2}'`
if [ "$PID" = "" ]; then
	echo "Process $daemon is not running"
else
	pkill $daemon
fi
}

kill_controller () {
controller="gvpn_controller.py"
PID=`ps -ef | grep $controller | grep -v grep | awk '{print $2}'`
if [ "$PID" = "" ]; then
	echo "Process $controller is not running"
else
	kill $PID
fi
}

kill_ipop_tincan
kill_controller
